### ISSUE TITLE
Items not removed from queue after run

### ISSUE THREAD

**Issue by morremeyer** [mend/renovate-ce-ee#363]
While debugging #357, I discovered that the queue does not work as I'd expect. I decided to document the differences here so that the current state can be clarified and documented as well as the current bug(s?) fixed.

## Expected behaviour

- I expect the queue size to be theoretically unlimited (and practically by e.g. memory and storage).
- I'd expect the API to be able to return all jobs in the queue, maybe using pagination

Picking up jobs:

1. Whenever no job is running, the first job in the queue is picked up and run
2. When a job is picked up, it is removed from the queue

Adding jobs:

- Jobs are added in the queue based on their priority
- A new job is added **behind** all existing jobs with the same priority (first come first serve for the same priority)
- Newly discovered repositories are added with low priority (covered in #357)

## Actual behaviour/Observations

_Running CE 6.1.1_

When we start renovate-ce from scratch (meaning there is no SQLite database yet), the following happens:

1. The AppSync discovers all repositories for the GitHub organizations we're running for (9 organizations)
2. It fills the queue and starts running on the repositories in the queue as designed.
3. When a repository is done, it is **not** removed from the queue
4. When CE has run on all repositories listed in the queue that are in the **same GitHub organization** (as per the `/api/job/queue` endpoint), the **first** repository in the queue is removed and **one** new one appears at the end of the list returned by the `/api/job/queue` endpoint. (in our case, the new ones are always from another organization since the organization we run on first has only 95 repositories)
5. All repositories in the queue that are **not** part of the first organization are ignored
6. CE logs `{"name":"renovate","hostname":"renovate-mend-renovate-ce-69f98cc768-hzvfc","pid":13920,"level":20,"logContext":"z25uOIeDKetLenwNJ0-Sd","msg":"Autodiscovering GitHub repositories","time":"2023-10-09T09:04:34.791Z","v":0}`
7. CE starts again at the beginning of the queue, effectively running again on all repositories but the first

I have observed this for a few full cycles through the queue, but not for the presumably 4560 (95+94+…+1) runs it would take to iterate through all repos of the first organization until they have all been removed from the queue.

I can share logs for this, however with the amount of redaction I'd have to do, I first want to find out if that's necessary to reproduce this. 

It looks to me like it can be reproduced with any combination of multiple GitHub organizations. I can build a full test setup at a later point in time, but hope that this will not be necessary.

**Comment by Gabriel-Ladzaretti** [comment]
Thank you for your detailed feedback!

1. Updated job priority mapping was merged and will will be released soon.
future releases will also have the ability to disable completely queueing jobs on startup, which will address issues when not persisting the db.
3. Currently jobs are only removed if the job was successfully completed but might be refined/changed later on
4. We will soon have a status api endpoint which will have much more information about queues and more
5. AppSync iterates organizations in order, therefore orgs will be queued one after the other.
4, 6 - 7. I assume you are using cli side `autodiscover` mode (based on the log message), You should instead rely on server side autodiscovering and not cli side (which is the default behavior for GitHub). Note that server side `autodiscoverFilter` is work in progress (so this is applicable only if you rely on it).


if emptying the queue takes more than an hour, i suggest adjusting the job queueing cron setting.

overall, when disabling cli side `autodiscover` + adjusting the job queueing schedule, the current behavior should be similar to what mentioned in the expected behavior.

**Comment by morremeyer** [comment]
Thanks for the explanation! That makes a lot of sense, I'll turn off the client side autodiscover and rely on AppSync exclusively once the server side `autodiscoverFilter` work is implemented.

I'll follow along to give it another test once that is available.

**Comment by nabeelsaabna** [comment]
should be handled by the new release `6.3.0`

**Comment by morremeyer** [comment]
This is resolved with `6.3.0`, I can confirm that.
