### ISSUE TITLE
RENOVATE_BINARY_SOURCE=install by default in full version

### ISSUE THREAD

**Issue by jgarec** [mend/renovate-ce-ee#402]
Hello,

I think the value of RENOVATE_BINARY_SOURCE is invalid, it should be `global` instead of `install` ?

Renovate doc : 
> Starting in v36, Renovate's default Docker image (previously referred to as the "slim" image) uses binarySource=install while the "full" Docker image uses binarySource=global

```
docker run -it --rm ghcr.io/mend/renovate-ce:6.7.0-full sh -c "set | egrep -i binary"
RENOVATE_BINARY_SOURCE='install'
```

**Comment by Gabriel-Ladzaretti** [comment]
'install' is actually the current value, it will install at runtime the resolved binary needed as opposed to 'global'.
furthermore, if the resolved binary is already installed, it will simply use that.

**Comment by rarkins** [comment]
This is a different product/image to the Renovate OSS images so that documentation does not strictly apply, although there's some argument in favor of making it the same as in the OSS (full=global, slim=install).

I think we're probably best to set binarySource=global for the full image, although I don't know if we can treat that as a fix or it should be a full breaking change

**Comment by nabeelsaabna** [comment]
so is it a fix or a breaking change ? 😃

**Comment by rarkins** [comment]
Yes, so let's do it in the next major
