### ISSUE TITLE
Merge confidence token as host rule VS env MEND_RNV_MC_TOKEN

### ISSUE THREAD

**Issue by mikaello** [mend/renovate-ce-ee#488]
In the [matchConfidence documentation](https://docs.renovatebot.com/configuration-options/#matchconfidence) it is described how to set the merge confidence token:

> Tokens can be configured via `hostRules` using the `"merge-confidence"` `hostType`:
> 
> ```json
> {
>   "hostRules":  [
>     {
>       "hostType":  "merge-confidence",
>       "token":  "********"
>     }
>   ]
> }
> ```

What is the difference from setting it as `hostRule` compared to setting it as the environment variable `MEND_RNV_MC_TOKEN` (which is described as "_The authentication token required when using Merge Confidence Workflows_")?

**Comment by Gabriel-Ladzaretti** [comment]
When `MEND_RNV_MC_TOKEN` is set, the mentioned host rule will be generated and injected with each job. When set to `auto`, it will also provision the token, fetching and refreshing it as needed.

So, if you have a static token (which I'll assume you don't, as we don't usually issue these), the difference is negligible, as the host rule is 'static' and never changes.

Otherwise, if you have are using `Renovate EE` and `MEND_RNV_MC_TOKEN=auto` is set, the host rule might change at runtime due to token refresh, etc.

**Comment by mikaello** [comment]
Thanks for getting back to me @Gabriel-Ladzaretti! 

I got a static token and are using Renovate EE, so in my case I can just go with `MEND_RNV_MC_TOKEN`, and skip setting `hostRules`?

In which cases does it makes sense to define `hostRules` instead of using `MEND_RNV_MC_TOKEN`?

**Comment by Gabriel-Ladzaretti** [comment]
> I got a static token and am using Renovate EE, so in my case I can just go with MEND_RNV_MC_TOKEN, and skip setting hostRules?

Yep. 

> In which cases does it makes sense to define hostRules instead of using MEND_RNV_MC_TOKEN?

Result-wise both are the same, the env var will just do the host rule for you.

**Comment by mikaello** [comment]
I think a difference between the two approaches is where [`RENOVATE_X_MERGE_CONFIDENCE_API_BASE_URL`](https://docs.renovatebot.com/self-hosted-experimental/#renovate_x_merge_confidence_api_base_url) must be defined. 

Previously, when using the token as a host rule it was the workers that needed the base URL variable, but when using the env `MEND_RNV_MC_TOKEN` the base URL had to be defined in the server.
